### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by holms** [alexlafroscia/yaml-merge#3]
Am I something doing wrong?

```
Romans-iMac:spiral_ai holms$ yaml-merge compose.yml compose.prod.env.yml compose.prod.yml cloud.prod.yml > cloud.yml
/opt/local/lib/node_modules/@alexlafroscia/yaml-merge/bin/yaml-merge:11
const outputFile = yamlMerge(...files);
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by alexlafroscia** [comment]
What's your node version? That's the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) which should work in anything later than `5.12.0` according to http://node.green/

**Comment by holms** [comment]
After instalilng `n` and updating to `stable` also as linking
/opt/local/…/npm to /usr/local/…/npm everything started to work.

OSX has issues apparently with npm :(


On July 5, 2017 at 10:30:50 PM, Alex LaFroscia (notifications@github.com)
wrote:

What's your node version? That's the spread operator
<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator>
which should work in anything later than 5.12.0 according to
http://node.green/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexlafroscia/yaml-merge/issues/3#issuecomment-313203156>,
or mute the thread

**Comment by alexlafroscia** [comment]
Huh, alright! Glad all is working for you :)
